/**
 * NIRF Engineering category — input field catalog.
 *
 * Generated from the official NIRF 2025 Engineering data-submission format
 * (institution credentials PDF, nirfindia.org/nirfpdfcdn/2025/framework/Engineering.pdf
 * and the corresponding data submitted by institutions that is published by NIRF).
 *
 * Each field carries the metadata required by the product spec:
 * field_id, parameter, sub_parameter, official_field_name, description,
 * data_type, unit, source_section, required_or_optional, validation_rule,
 * calculation_dependency, formula_reference.
 */

import type { FieldMetadata } from "./types";

export const ENGINEERING_FIELDS: FieldMetadata[] = [
  // ── Institution details ──────────────────────────────────────────────
  {
    fieldId: "INST_001",
    key: "instituteName",
    parameter: "INST",
    subParameter: "Institution Identity",
    officialFieldName: "Name of the Institution",
    shortLabel: "Institution Name",
    description: "Full legal name of the institute as registered on the NIRF portal.",
    dataType: "string",
    sourceSection: "Institute details (cover page)",
    class: "mandatory",
    required: true,
    validationRule: "Non-empty string (<= 200 chars).",
  },
  {
    fieldId: "INST_002",
    key: "instituteId",
    parameter: "INST",
    subParameter: "Institution Identity",
    officialFieldName: "NIRF Institute ID",
    shortLabel: "Institute ID",
    description: "NIRF portal registration id, e.g. IR-E-U-0456.",
    dataType: "string",
    sourceSection: "Institute details (cover page)",
    class: "mandatory",
    required: true,
    validationRule: "Matches ^IR-E-[A-Z]-\\d+$ pattern.",
  },

  // ── TLR: SS ──────────────────────────────────────────────────────────
  {
    fieldId: "TLR_001",
    key: "sanctionedIntake",
    parameter: "TLR",
    subParameter: "SS — Student Strength (aimed: total sanctioned intake NT)",
    officialFieldName: "Total sanctioned intake (UG + PG, per year)",
    shortLabel: "Sanctioned Intake (NT)",
    description: "Total sanctioned intake of students across UG and PG programmes.",
    dataType: "integer",
    unit: "students",
    sourceSection: "Student Enrolment details (UG/PG tables)",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative integer. Must be >= 0.",
    calculationDependencies: ["SS", "FSR", "GPH", "GUE"],
    formulaReference: "SS = f(NT, NE)", 
  },
  {
    fieldId: "TLR_002",
    key: "enrolledStudents",
    parameter: "TLR",
    subParameter: "SS — Student Strength (students enrolled NE)",
    officialFieldName: "Total students enrolled (UG + PG)",
    shortLabel: "Enrolled Students (NE)",
    description: "Total number of students enrolled.",
    dataType: "integer",
    unit: "students",
    sourceSection: "Student Enrolment details (UG/PG tables)",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative integer.",
    calculationDependencies: ["SS", "FRU", "FSR", "RD", "WD", "ESCS", "GPH"],
    formulaReference: "SS = f(NT, NE)",
  },
  {
    fieldId: "TLR_003",
    key: "phdStudents",
    parameter: "TLR",
    subParameter: "SS — Student Strength (doctoral students NP)",
    officialFieldName: "Number of full-time and part-time PhD students",
    shortLabel: "PhD Students Enrolled (NP)",
    description: "Doctoral (PhD) students enrolled in research programmes.",
    dataType: "integer",
    unit: "students",
    sourceSection: "Student Enrolment details (PhD)",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative integer. Part of total enrolment (NP <= NE + NP definition).",
    calculationDependencies: ["SS", "FSR", "FRU"],
    formulaReference: "FSR uses N = NT + NP",
  },

  // ── TLR: FSR / FQE / FRU ─────────────────────────────────────────────
  {
    fieldId: "TLR_004",
    key: "permanentFaculty",
    parameter: "TLR",
    subParameter: "FSR — Faculty-Student Ratio",
    officialFieldName: "Number of full-time regular (permanent) faculty",
    shortLabel: "Permanent Faculty (F)",
    description: "Faculty employed on a full-time regular basis.",
    dataType: "integer",
    unit: "faculty",
    sourceSection: "Faculty Details",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative integer.",
    calculationDependencies: ["FSR", "FQE", "FRQ", "WD"],
    formulaReference: "FSR = 30 × min(15 × F/(NT+NP), 1)",
  },
  {
    fieldId: "TLR_005",
    key: "facultyWithPhD",
    parameter: "TLR",
    subParameter: "FQE — Faculty with PhD (FQE)",
    officialFieldName: "Number of faculty with PhD (or equivalent qualification)",
    shortLabel: "Faculty with PhD",
    description: "Faculty holding a doctoral degree or equivalent.",
    dataType: "integer",
    unit: "faculty",
    sourceSection: "Faculty Details",
    class: "needed",
    required: false,
    min: 0,
    maxPercent: 100,
    validationRule: "0 <= value <= permanentFaculty.",
    calculationDependencies: ["FQE"],
    formulaReference: "FQE = FQ + FE; FQ from % faculty with PhD",
  },
  {
    fieldId: "TLR_006",
    key: "facultyExp0to8",
    parameter: "TLR",
    subParameter: "FQE — Faculty experience 0 to 8 years",
    officialFieldName: "Faculty with total experience 0-8 years",
    shortLabel: "Faculty Exp 0–8 yrs",
    description: "Number of faculty whose teaching/research experience is up to 8 years.",
    dataType: "integer",
    unit: "faculty",
    sourceSection: "Faculty Details",
    class: "needed",
    required: false,
    min: 0,
    validationRule: "Sum of experience bands should not exceed permanentFaculty by more than a small tolerance.",
    calculationDependencies: ["FQE"],
    formulaReference: "FE = 3×min(3F1,1) + 3×min(3F2,1) + 4×min(3F3,1)",
  },
  {
    fieldId: "TLR_007",
    key: "facultyExp8to15",
    parameter: "TLR",
    subParameter: "FQE — Faculty experience 8 to 15 years",
    officialFieldName: "Faculty with total experience 8-15 years",
    shortLabel: "Faculty Exp 8–15 yrs",
    description: "Number of faculty whose experience is between 8 and 15 years.",
    dataType: "integer",
    unit: "faculty",
    sourceSection: "Faculty Details",
    class: "needed",
    required: false,
    min: 0,
    validationRule: "Sum of experience bands should not exceed permanentFaculty by more than a small tolerance.",
    calculationDependencies: ["FQE"],
    formulaReference: "FE = 3×min(3F2,1) + ...",
  },
  {
    fieldId: "TLR_008",
    key: "facultyExp15plus",
    parameter: "TLR",
    subParameter: "FQE — Faculty experience above 15 years",
    officialFieldName: "Faculty with total experience greater than 15 years",
    shortLabel: "Faculty Exp 15+ yrs",
    description: "Number of faculty whose experience exceeds 15 years.",
    dataType: "integer",
    unit: "faculty",
    sourceSection: "Faculty Details",
    class: "needed",
    required: false,
    min: 0,
    validationRule: "Sum of experience bands should not exceed permanentFaculty by more than a small tolerance.",
    calculationDependencies: ["FQE"],
    formulaReference: "FE = ... + 4×min(3F3,1)",
  },
  {
    fieldId: "TLR_009",
    key: "capitalExpenditure",
    parameter: "TLR",
    subParameter: "FRU — Financial Resources and Utilisation",
    officialFieldName: "Annual capital expenditure (BC)",
    shortLabel: "Capital Expenditure (BC)",
    description: "Capital expenditure incurred during the year (INR).",
    dataType: "number",
    unit: "INR",
    sourceSection: "Financial Resources (Fixed Assets, Library, etc.)",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative. Monetary value in rupees.",
    calculationDependencies: ["FRU"],
    formulaReference: "FRU uses BC (capital) + BO (operational) expenditure",
  },
  {
    fieldId: "TLR_010",
    key: "operationalExpenditure",
    parameter: "TLR",
    subParameter: "FRU — Financial Resources and Utilisation",
    officialFieldName: "Annual operational expenditure (BO)",
    shortLabel: "Operational Expenditure (BO)",
    description: "Operational / running expenditure during the year (INR).",
    dataType: "number",
    unit: "INR",
    sourceSection: "Financial Resources (Salaries, consumables, seminars)",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative. Monetary value in rupees.",
    calculationDependencies: ["FRU"],
    formulaReference: "FRU uses BC + BO expenditure per student",
  },

  // ── RP: PU / QP / IPR / FPPP ─────────────────────────────────────────
  {
    fieldId: "RP_001",
    key: "totalPublications",
    parameter: "RP",
    subParameter: "PU — Publications",
    officialFieldName: "Total number of research publications (bibliometric year)",
    shortLabel: "Total Publications (P)",
    description: "Publications in Scopus/WoS-indexed peer-reviewed venues over the window.",
    dataType: "integer",
    unit: "publications",
    sourceSection: "Research Publications & Citations",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative integer.",
    calculationDependencies: ["PU", "QP", "FRQ"],
    formulaReference: "PU = 35 × f(P/FRQ); QP uses citations",
  },
  {
    fieldId: "RP_002",
    key: "totalCitations",
    parameter: "RP",
    subParameter: "QP — Quality of Publications (citations)",
    officialFieldName: "Total number of citations",
    shortLabel: "Total Citations (CC)",
    description: "Total citations received by the institution's publications.",
    dataType: "integer",
    unit: "citations",
    sourceSection: "Research Publications & Citations",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative integer.",
    calculationDependencies: ["QP"],
    formulaReference: "QP = 20×f(CC/FRQ) + 20×f(TOP25%/P) - 5×f(Cret/FRQ)",
  },
  {
    fieldId: "RP_003",
    key: "top25Citations",
    parameter: "RP",
    subParameter: "QP — Quality of Publications (top 25%)",
    officialFieldName: "Citations in top-25% journals",
    shortLabel: "Citations in Top-25% Journals",
    description: "Citations attributable to publications in top 25% journals.",
    dataType: "integer",
    unit: "citations",
    sourceSection: "Research Publications & Citations",
    class: "needed",
    required: false,
    min: 0,
    validationRule: "0 <= value <= totalCitations.",
    calculationDependencies: ["QP"],
    formulaReference: "QP = ... + 20×f(TOP25%/P)",
  },
  {
    fieldId: "RP_004",
    key: "patentsFiled",
    parameter: "RP",
    subParameter: "IPR — IPR and Patents",
    officialFieldName: "Patents published / filed",
    shortLabel: "Patents Filed/Published (IPP)",
    description: "Patents filed and published by the institution.",
    dataType: "integer",
    unit: "patents",
    sourceSection: "IPR / Patents",
    class: "needed",
    required: false,
    min: 0,
    validationRule: "Non-negative integer.",
    calculationDependencies: ["IPR"],
    formulaReference: "IPR = 10×f(IPG) + 5×f(IPP)",
  },
  {
    fieldId: "RP_005",
    key: "patentsGranted",
    parameter: "RP",
    subParameter: "IPR — IPR and Patents",
    officialFieldName: "Patents granted",
    shortLabel: "Patents Granted (IPG)",
    description: "Patents granted to the institution.",
    dataType: "integer",
    unit: "patents",
    sourceSection: "IPR / Patents",
    class: "needed",
    required: false,
    min: 0,
    validationRule: "Non-negative integer.",
    calculationDependencies: ["IPR"],
    formulaReference: "IPR = 10×f(IPG) + 5×f(IPP)",
  },
  {
    fieldId: "RP_006",
    key: "sponsoredResearchAmount",
    parameter: "RP",
    subParameter: "FPPP — Projects and Professional Practice",
    officialFieldName: "Sponsored research funds received (RF)",
    shortLabel: "Sponsored Research Funds (RF)",
    description: "Sponsor research funds received (INR).",
    dataType: "number",
    unit: "INR",
    sourceSection: "Sponsored Research Details",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative monetary value.",
    calculationDependencies: ["FPPP", "FRU"],
    formulaReference: "FPPP = 7.5×f(RF/FRQ) + 2.5×f(CF/FRQ)",
  },
  {
    fieldId: "RP_007",
    key: "consultancyRevenue",
    parameter: "RP",
    subParameter: "FPPP — Projects and Professional Practice",
    officialFieldName: "Consultancy revenue received (CF)",
    shortLabel: "Consultancy Revenue (CF)",
    description: "Consultancy project revenue received (INR).",
    dataType: "number",
    unit: "INR",
    sourceSection: "Consultancy Project Details",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative monetary value.",
    calculationDependencies: ["FPPP", "FRU"],
    formulaReference: "FPPP = 7.5×f(RF/FRQ) + 2.5×f(CF/FRQ)",
  },
  {
    fieldId: "RP_008",
    key: "retractedPapers",
    parameter: "RP",
    subParameter: "PU/QP — Retraction penalty",
    officialFieldName: "Number of retracted publications",
    shortLabel: "Retracted Papers (Pret)",
    description: "Retracted publications in the window (penalty).",
    dataType: "integer",
    unit: "publications",
    sourceSection: "Retraction Details",
    class: "optional",
    required: false,
    min: 0,
    validationRule: "0 <= value <= totalPublications.",
    calculationDependencies: ["PU", "RP_PENALTY"],
    formulaReference: "PU = 35×f(P/FRQ) - 5×f(Pret/FRQ)",
  },
  {
    fieldId: "RP_009",
    key: "retractedCitations",
    parameter: "RP",
    subParameter: "PU/QP — Retraction penalty",
    officialFieldName: "Citations of retracted publications",
    shortLabel: "Retracted Citations (Cret)",
    description: "Citations belonging to retracted publications (penalty).",
    dataType: "integer",
    unit: "citations",
    sourceSection: "Retraction Details",
    class: "optional",
    required: false,
    min: 0,
    validationRule: "0 <= value <= totalCitations.",
    calculationDependencies: ["QP", "RP_PENALTY"],
    formulaReference: "QP = ... - 5×f(Cret/FRQ)",
  },

  // ── GO ───────────────────────────────────────────────────────────────
  {
    fieldId: "GO_001",
    key: "graduatesPlaced",
    parameter: "GO",
    subParameter: "GPH — Placement and Higher Studies",
    officialFieldName: "Number of students placed (Np)",
    shortLabel: "Graduates Placed (Np)",
    description: "Graduates placed in companies / organisations.",
    dataType: "integer",
    unit: "students",
    sourceSection: "Graduation Outcomes / Placement",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative integer.",
    calculationDependencies: ["GPH"],
    formulaReference: "GPH = 40 × g((Np + Nhs)/NT)",
  },
  {
    fieldId: "GO_002",
    key: "graduatesHigherStudies",
    parameter: "GO",
    subParameter: "GPH — Placement and Higher Studies",
    officialFieldName: "Number of graduates pursuing higher studies (Nhs)",
    shortLabel: "Graduates in Higher Studies (Nhs)",
    description: "Graduates admitted to higher studies.",
    dataType: "integer",
    unit: "students",
    sourceSection: "Graduation Outcomes / Higher Studies",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative integer.",
    calculationDependencies: ["GPH"],
    formulaReference: "GPH = 40 × g((Np + Nhs)/NT)",
  },
  {
    fieldId: "GO_003",
    key: "graduatesInTime",
    parameter: "GO",
    subParameter: "GUE — University Examinations",
    officialFieldName: "Number of graduates completing in stipulated time (Ng)",
    shortLabel: "Graduates in Stipulated Time (Ng)",
    description: "Graduates who completed the programme within the stipulated time.",
    dataType: "integer",
    unit: "students",
    sourceSection: "Graduation Outcomes / Examination results",
    class: "needed",
    required: false,
    min: 0,
    validationRule: "Non-negative integer.",
    calculationDependencies: ["GUE"],
    formulaReference: "GUE = 15 × min(Ng/(0.8×NT), 1)",
  },
  {
    fieldId: "GO_004",
    key: "medianSalary",
    parameter: "GO",
    subParameter: "GMS — Median Salary",
    officialFieldName: "Median salary of placed graduates (MS)",
    shortLabel: "Median Salary (MS)",
    description: "Median annual salary of graduates (INR/year).",
    dataType: "number",
    unit: "INR/year",
    sourceSection: "Graduation Outcomes / Placement salary details",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative monetary value.",
    calculationDependencies: ["GMS"],
    formulaReference: "GMS = 25 × f(MS)",
  },
  {
    fieldId: "GO_005",
    key: "phdGraduates",
    parameter: "GO",
    subParameter: "GPHD — PhD Graduates",
    officialFieldName: "Number of PhD students graduated (Nphd)",
    shortLabel: "PhD Graduated (Nphd)",
    description: "Doctoral degrees awarded in the window.",
    dataType: "integer",
    unit: "students",
    sourceSection: "Graduation Outcomes / PhD details",
    class: "mandatory",
    required: true,
    min: 0,
    validationRule: "Non-negative integer.",
    calculationDependencies: ["GPHD"],
    formulaReference: "GPHD = 20 × f(Nphd)",
  },

  // ── OI ───────────────────────────────────────────────────────────────
  {
    fieldId: "OI_001",
    key: "womenStudents",
    parameter: "OI",
    subParameter: "WD — Women Diversity (students)",
    officialFieldName: "Number of women students enrolled (NWS)",
    shortLabel: "Women Students (NWS)",
    description: "Women students among total enrolment.",
    dataType: "integer",
    unit: "students",
    sourceSection: "Student Enrolment details",
    class: "mandatory",
    required: true,
    min: 0,
    maxPercent: 100,
    validationRule: "0 <= value <= total students enrolled.",
    calculationDependencies: ["WD"],
    formulaReference: "WD = A×f(NWS/(TWS×total)) + B×f(NWF/(TWF×F))",
  },
  {
    fieldId: "OI_002",
    key: "womenFaculty",
    parameter: "OI",
    subParameter: "WD — Women Diversity (faculty)",
    officialFieldName: "Number of women faculty (NWF)",
    shortLabel: "Women Faculty (NWF)",
    description: "Women faculty among permanent faculty.",
    dataType: "integer",
    unit: "faculty",
    sourceSection: "Faculty Details",
    class: "needed",
    required: false,
    min: 0,
    maxPercent: 100,
    validationRule: "0 <= value <= permanentFaculty.",
    calculationDependencies: ["WD"],
    formulaReference: "WD = A×f(NWS/(TWS×total)) + B×f(NWF/(TWF×F))",
  },
  {
    fieldId: "OI_003",
    key: "studentsOtherStates",
    parameter: "OI",
    subParameter: "RD — Region Diversity",
    officialFieldName: "Students from other states",
    shortLabel: "Students from Other States",
    description: "Enrolled students domiciled outside the institution's state.",
    dataType: "integer",
    unit: "students",
    sourceSection: "Student Enrolment details",
    class: "mandatory",
    required: true,
    min: 0,
    maxPercent: 100,
    validationRule: "0 <= value <= total students enrolled.",
    calculationDependencies: ["RD"],
    formulaReference: "RD = 25×f(otherStates/total) + 5×f(otherCountries/total)",
  },
  {
    fieldId: "OI_004",
    key: "studentsOtherCountries",
    parameter: "OI",
    subParameter: "RD — Region Diversity",
    officialFieldName: "Students from other countries",
    shortLabel: "Students from Other Countries",
    description: "Enrolled students from foreign countries.",
    dataType: "integer",
    unit: "students",
    sourceSection: "Student Enrolment details",
    class: "mandatory",
    required: true,
    min: 0,
    maxPercent: 100,
    validationRule: "0 <= value <= total students enrolled.",
    calculationDependencies: ["RD"],
    formulaReference: "RD = 25×f(otherStates/total) + 5×f(otherCountries/total)",
  },
  {
    fieldId: "OI_005",
    key: "escsStudents",
    parameter: "OI",
    subParameter: "ESCS — Economically/Socially Challenged",
    officialFieldName: "Students from economically/socially challenged sections (Nesc)",
    shortLabel: "ESCS Students (Nesc)",
    description: "Students belonging to economically/socially challenged sections.",
    dataType: "integer",
    unit: "students",
    sourceSection: "Student Enrolment details",
    class: "mandatory",
    required: true,
    min: 0,
    maxPercent: 100,
    validationRule: "0 <= value <= total students enrolled.",
    calculationDependencies: ["ESCS"],
    formulaReference: "ESCS = 20 × f(Nesc/(share×total))",
  },
  {
    fieldId: "OI_006",
    key: "pcsFacilities",
    parameter: "OI",
    subParameter: "PCS — Facilities for Physically Challenged",
    officialFieldName: "Facilities for physically challenged students",
    shortLabel: "PCS Facilities",
    description: "Whether adequate facilities for persons with disabilities exist.",
    dataType: "boolean",
    sourceSection: "Facilities of Physically Challenged",
    class: "mandatory",
    required: true,
    validationRule: "Boolean (Yes/No derived from facilities table).",
    calculationDependencies: ["PCS"],
    formulaReference: "PCS = 20 if facilities complete as per official checklist",
  },

  // ── PR ───────────────────────────────────────────────────────────────
  {
    fieldId: "PR_001",
    key: "perceptionScore",
    parameter: "PR",
    subParameter: "PR — Perception (peer + employer)",
    officialFieldName: "Perception score (Academic Peers + Employers)",
    shortLabel: "Perception Score",
    description: "NIRF perception score from peer and employer surveys, 0-100. Not part of submitted credentials; published by NIRF.",
    dataType: "number",
    unit: "0-100",
    sourceSection: "Not in credentials — perception survey",
    class: "optional",
    required: false,
    min: 0,
    max: 100,
    minPercent: 0,
    maxPercent: 100,
    validationRule: "0 <= value <= 100.",
    calculationDependencies: ["PR"],
    formulaReference: "PR = Perception(100), 0.10 weight",
  },
];

export const ENGINEERING_FIELDS_BY_KEY: Map<string, FieldMetadata> = new Map(
  ENGINEERING_FIELDS.map((f) => [f.key, f])
);

export const ENGINEERING_FIELDS_BY_ID: Map<string, FieldMetadata> = new Map(
  ENGINEERING_FIELDS.map((f) => [f.fieldId, f])
);